{{- if eq .Values.redis.provider "standalone" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-redis-headless
  labels: {{ include "featurebyte-oss.labels.redis" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{ include "featurebyte-oss.selectorLabels.redis" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-redis
  labels: {{ include "featurebyte-oss.labels.redis" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "featurebyte-oss.selectorLabels.redis" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
{{- end }}