version: 3

vars:
  NAMESPACE: featurebyte
  KUBE_CONTEXT: k3d-featurebyte

tasks:
  dev:
    desc: Start development environment
    cmds:
      - task: k3d-init
      - task: k3d-start
      - task: mongodb-operator
      - task: dev-start

  dev-clean:
    desc: Clean development environment
    deps:
      - task: dev-stop
    cmds:
      - k3d cluster delete featurebyte

  dev-start:
    desc: Install/Upgrade helm chart
    run: once
    dir: charts/featurebyte-oss
    cmds:
      - helm upgrade dev . -n {{.NAMESPACE}} --create-namespace --install --dependency-update --kube-context {{.KUBE_CONTEXT}} -f values.yaml

  dev-stop:
    desc: Uninstall helm chart
    cmds:
      - helm uninstall dev -n featurebyte --kube-context {{.KUBE_CONTEXT}}

  dev-down:
    run: once
    desc: Stop development environment
    cmds:
      - task: dev-stop
      - task: k3d-stop

  k3d-init:
    desc: Initialize k3d cluster
    run: once
    ignore_error: true
    interactive: true
    status:
      - k3d cluster list featurebyte
    cmds:
      - k3d cluster create featurebyte --api-port 6443 --port "80:80@loadbalancer" --port "443:80@loadbalancer" --registry-create featurebyte.localhost:10443

  k3d-start:
    desc: Start k3d cluster
    run: once
    cmds:
      - k3d cluster start featurebyte

  k3d-stop:
    desc: Stop development environment
    cmds:
      - k3d cluster stop featurebyte

  mongodb-operator:
    desc: Install MongoDB Operator
    deps:
      - k3d-start
    status:
      - helm status community-operator -n {{.NAMESPACE}}
    cmds:
      - helm upgrade community-operator community-operator --kube-context {{.KUBE_CONTEXT}} --namespace {{.NAMESPACE}} --create-namespace --install --repo=https://mongodb.github.io/helm-charts

# DEBUGGING COMMANDS
  dev-local:
    dir: charts/featurebyte-oss
    cmds:
      - helm upgrade dev . -n {{.NAMESPACE}} --create-namespace --install --kube-context {{.KUBE_CONTEXT}} --dependency-update -f values.yaml,dev-values.yaml
  helm-template:
    dir: charts/featurebyte-oss
    cmds:
      - helm template featurebyte-oss . -n {{.NAMESPACE}} --kube-context {{.KUBE_CONTEXT}} --debug

  test-plugins:
    internal: true
    status:
      - helm plugin list | grep "unittest"
    cmds:
      - helm plugin install https://github.com/helm-unittest/helm-unittest.git

  test:
    dir: charts/featurebyte-oss
    deps:
      - task: test-plugins
    cmds:
      - helm unittest . 
