version: 3

vars:
  NAMESPACE: featurebyte

tasks:
  dev:
    desc: Start development environment
    cmds:
      - task: k3d-init
      - task: k3d-start
      - task: mongodb-operator
      - task: dev-start

  dev-clean:
    desc: Clean development environment
    deps:
      - task: dev-stop
    cmds:
      - k3d cluster delete featurebyte

  dev-start:
    desc: Install/Upgrade helm chart
    run: once
    cmds:
      - helm upgrade dev charts/featurebyte-oss -n {{.NAMESPACE}} --create-namespace --install --dependency-update

  dev-stop:
    desc: Uninstall helm chart
    cmds:
      - helm uninstall dev -n featurebyte

  dev-down:
    run: once
    desc: Stop development environment
    cmds:
      - task: dev-stop
      - task: k3d-stop

  k3d-init:
    desc: Initialize k3d cluster
    run: once
    ignore_error: true
    interactive: true
    status:
      - k3d cluster list featurebyte
    cmds:
      - k3d cluster create featurebyte --api-port 6443 --port "80:80@loadbalancer" --port "443:80@loadbalancer" --registry-create featurebyte.localhost:10443

  k3d-start:
    desc: Start k3d cluster
    run: once
    cmds:
      - k3d cluster start featurebyte

  k3d-stop:
    desc: Stop development environment
    cmds:
      - k3d cluster stop featurebyte

  mongodb-operator:
    desc: Install MongoDB Operator
    deps:
      - k3d-start
    status:
      - helm status community-operator -n {{.NAMESPACE}}
    cmds:
      - helm upgrade community-operator community-operator --namespace {{.NAMESPACE}} --create-namespace --install --repo=https://mongodb.github.io/helm-charts

# DEBUGGING COMMANDS
  helm-template:
    dir: charts/featurebyte-oss
    cmds:
      - helm template featurebyte-oss . -n {{.NAMESPACE}} --debug