version: 3

tasks:
  dev:
    desc: Start development environment
    cmds:
      - task: dev-init
      - task: dev-start
      - task: dev-helm

  dev-init:
    ignore_error: true
    interactive: true
    run: once
    cmds:
      - k3d cluster create featurebyte --api-port 6443 --port "80:80@loadbalancer" --port "443:80@loadbalancer" --registry-create localhost:10443

  dev-start:
    desc: Start k3d cluster
    cmds:
      - k3d cluster start featurebyte

  dev-stop:
    desc: Stop development environment
    cmds:
      - k3d cluster stop featurebyte

  dev-clean:
    desc: Clean development environment
    deps:
      - task: dev-stop
    cmds:
      - k3d cluster delete featurebyte

  dev-helm:
    desc: Install featurebyte-oss
    aliases:
      - dev-helm-install
    deps:
      - mongodb-operator
    cmds:
      - helm upgrade dev charts/featurebyte-oss -n featurebyte --create-namespace --install --dependency-update

  dev-helm-uninstall:
    cmds:
      - helm uninstall dev -n featurebyte

  mongodb-operator:
    desc: Install MongoDB Operator
    deps:
      - dev-start
    status:
      - helm status community-operator -n featurebyte
    cmds:
      - helm upgrade community-operator community-operator --namespace featurebyte --create-namespace --install --repo=https://mongodb.github.io/helm-charts