apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-api
  labels: {{ include "featurebyte-oss.labels.api" . | nindent 4 }}
spec:
  {{- if not .Values.featurebyte.api.autoscaling.enabled }}
  replicas: {{ .Values.featurebyte.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{ include "featurebyte-oss.selectorLabels.api" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "featurebyte-oss.labels.api" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "featurebyte-oss.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.featurebyte.api.image.repository }}:{{ default .Chart.AppVersion .Values.featurebyte.api.image.tag }}"
          imagePullPolicy: {{ .Values.featurebyte.api.image.pullPolicy }}
          command: ["bash", "/docker-entrypoint.sh", "server"]
          env:
            - name: FEATUREBYTE_HOME
              value: "/app/.featurebyte"
            - name: MPLCONFIGDIR
              value: "/app/matplotlib"
            - name: API_HOST
              value: "0.0.0.0"
            - name: API_PORT
              value: "8088"
            {{- include "featurebyte-oss.env.mongodb" . | nindent 12 }}
            {{- include "featurebyte-oss.env.redis" . | nindent 12 }}
            {{- include "featurebyte-oss.env.s3" . | nindent 12 }}
            {{- if .Values.featurebyte.kerberos.enabled }}
            {{- include "featurebyte-oss.env.keberos" . | nindent 12 }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /status
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /status
              port: 8088
            periodSeconds: 10
          resources:
            {{- toYaml .Values.featurebyte.api.resources | nindent 12 }}
      {{- include "featurebyte-oss.podAffinity.api" . | indent 4 }}
