{{- if .Values.featurebyte.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-api
  labels: {{ include "featurebyte-oss.labels.api" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.featurebyte.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.featurebyte.api.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "featurebyte-oss.fullname" . }}-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.featurebyte.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}