apiVersion: v2
name: featurebyte-oss
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: community-operator
    version: 0.7.9
    repository: https://mongodb.github.io/helm-charts