featurebyte:
  api:
    image:
      repository: "registry.localhost:10443/featurebyte-server"
      tag: "latest"
      pullPolicy: Always
  worker:
    image:
      repository: "registry.localhost:10443/featurebyte-server"
      tag: "latest"
      pullPolicy: Always

mongodb:
  communityOperator:
    persistence:
      storageClass: "local-path"
      dataSize: "1G"
      logSize: "200M"

community-operator:
  registry:
    pullPolicy: IfNotPresent

# Enable access to localhost:80 to connect to the featurebyte-api server
ingress:
  enabled: true
  host: app.featurebyte.localhost
