featurebyte:
  api:
    image:
      repository: "registry.localhost:10443/featurebyte-server"
      tag: "latest"
      pullPolicy: Always
    resources:
      requests:
        cpu: 0
        memory: 0
  worker:
    image:
      repository: "registry.localhost:10443/featurebyte-server"
      tag: "latest"
      pullPolicy: Always
    resources:
      requests:
        cpu: 0
        memory: 0

s3:
  minio:
    persistence:
      storageClass: "local-path"
      size: "1G"

mongodb:
  communityOperator:
    persistence:
      storageClass: "local-path"
      dataSize: "1G"
      logSize: "200M"

redis:
  standalone:
    persistence:
      storageClass: "local-path"
      size: "200M"

community-operator:
  registry:
    pullPolicy: IfNotPresent

# Enable access to localhost:80 to connect to the featurebyte-api server
ingress:
  enabled: true
  host: app.featurebyte.localhost
