featurebyte:
  api:
    image:
      repository: "registry.localhost:10443/featurebyte-server"
  worker:
    image:
      repository: "registry.localhost:10443/featurebyte-server"

# Enable access to localhost:80 to connect to the featurebyte-api server
ingress:
  enabled: true