apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-api
  labels:
    {{- include "featurebyte-oss.labels.api" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    {{- include "featurebyte-oss.selectorLabels.api" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-api
  labels: {{ include "featurebyte-oss.labels.api" . | nindent 4 }}
spec:
  {{- if not .Values.featurebyte.api.autoscaling.enabled }}
  replicas: {{ .Values.featurebyte.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{ include "featurebyte-oss.selectorLabels.api" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "featurebyte-oss.labels.api" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "featurebyte-oss.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.featurebyte.api.image.repository }}:{{ .Values.featurebyte.api.image.tag }}"
          imagePullPolicy: {{ .Values.featurebyte.api.image.pullPolicy }}
          command: ["bash", "/docker-entrypoint.sh", "server"]
          env:
            - name: FEATUREBYTE_HOME
              value: "/app/.featurebyte"
            - name: MPLCONFIGDIR
              value: "/app/matplotlib"
            - name: API_HOST
              value: "0.0.0.0"
            - name: API_PORT
              value: "8088"
            - name: LOG_LEVEL
              value: "info"
            - name: LOCAL_UID
              value: "1000"
            - name: LOCAL_GID
              value: "1000"
            # This is a full mongodb connection string
            # The referenced secret is generated by the mongodb operator
            # TODO: Allow user to use their own mongodb
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "featurebyte-oss.fullname" . }}-mongodb-admin-featurebyte
                  key: connectionString.standard
            # TODO: allow user to use their own redis
            - name: REDIS_URI
              value: "redis://{{ include "featurebyte-oss.fullname" . }}-redis:6379"
          securityContext:
            {{- toYaml .Values.featurebyte.securityContext | nindent 12 }}
          startupProbe:
            httpGet:
              path: /status
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /status
              port: 8088
            periodSeconds: 10
          resources:
            {{- toYaml .Values.featurebyte.api.resources | nindent 12 }}
      {{- include "featurebyte-oss.podAffinity.api" . | indent 4 }}
---
{{- if .Values.featurebyte.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-api
  labels: {{ include "featurebyte-oss.labels.api" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.featurebyte.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.featurebyte.api.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "featurebyte-oss.fullname" . }}-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.featurebyte.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}