apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-redis-headless
  labels: {{ include "featurebyte-oss.labels.redis" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{ include "featurebyte-oss.selectorLabels.redis" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-redis
  labels: {{ include "featurebyte-oss.labels.redis" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "featurebyte-oss.selectorLabels.redis" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-redis
  labels: {{ include "featurebyte-oss.labels.redis" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "featurebyte-oss.fullname" . }}-redis-headless
  selector:
    matchLabels: {{ include "featurebyte-oss.selectorLabels.redis" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "featurebyte-oss.labels.redis" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "redis:7"
          command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi