apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-api
  labels:
    {{- include "featurebyte-oss.labels.api" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    {{- include "featurebyte-oss.selectorLabels.api" . | nindent 4 }}
