{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-minio
  labels: {{ include "featurebyte-oss.labels.minio" . | nindent 4 }}
spec:
  serviceName: {{ include "featurebyte-oss.fullname" . }}-minio-headless
  replicas: 1
  selector:
    matchLabels: {{ include "featurebyte-oss.selectorLabels.minio" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "featurebyte-oss.labels.minio" . | nindent 8 }}
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          command:
            - minio
            - server
            - "/data"
            - --console-address
            - ":9001"
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
{{- end }}