{{- if eq .Values.mongodb.provider "communityOperator" -}}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-mongodb
  labels: {{ include "featurebyte-oss.labels.mongodb" . | nindent 4 }}
spec:
  members: 2
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: featurebyte
      db: admin
      {{- if .Values.mongodb.communityOperator.passwordRef.enabled }}
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: {{ .Values.mongodb.communityOperator.passwordRef.name }}
        key: {{ .Values.mongodb.communityOperator.passwordRef.key }}
      {{- else }}
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: {{ include "featurebyte-oss.fullname" . }}-mongodb
      {{- end }}
      roles:
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: {{ include "featurebyte-oss.fullname" . }}-mongodb-scram
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            resources:
              requests:
                storage: {{ .Values.mongodb.communityOperator.persistence.dataSize | quote }}
            storageClassName: {{ .Values.mongodb.communityOperator.persistence.storageClass }}
        - metadata:
            name: logs-volume
          spec:
            resources:
              requests:
                storage: {{ .Values.mongodb.communityOperator.persistence.logSize | quote }}
            storageClassName: {{ .Values.mongodb.communityOperator.persistence.storageClass }}
  additionalMongodConfig:
    # the additional config passed to the mongod process can be specified
    # either in nested or dot notation
    storage.wiredTiger.engineConfig.journalCompressor: zlib
{{- end }}
