{{- if .Values.mongodb.enabled -}}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-mongodb
  labels: {{ include "featurebyte-oss.labels.mongodb" . | nindent 4 }}
spec:
  members: 2
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: featurebyte
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: {{ include "featurebyte-oss.fullname" . }}-mongodb
      roles:
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: {{ include "featurebyte-oss.fullname" . }}-mongodb-scram
  additionalMongodConfig:
    # the additional config passed to the mongod process can be specified
    # either in nested or dot notation
    storage.wiredTiger.engineConfig.journalCompressor: zlib
{{- end }}