{{- if not (eq .Values.mongodb.provider "communityOperator") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "featurebyte-oss.fullname" . }}-mongodb-external
  labels: {{- include "featurebyte-oss.labels.mongodb" . | nindent 4 }}
type: Opaque
stringData:
  connectionString.standard: "{{ .Values.mongodb.external.connectionStr }}"
{{- end }}
