name: "test"

on:
  pull_request:
    branches:
      - main

jobs:
  helm-unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run helm unittest (featurebyte-oss)
        uses: d3adb5/helm-unittest-action@v2
        with:
          helm-version: v3.12.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          chart-path: charts/featurebyte-oss